### ISSUE TITLE
Cannot get "Log in to file system" screen

### ISSUE THREAD

**Issue by josmithua** [ADARTA/gatsby-starter-netlify-cms#3]
Hi there,

I'm trying to get the file-system backend to work in my project but I cannot get the "Log in to file system" button on the /admin page. All I get is the following:

![Screen Shot 2019-09-07 at 19 26 31](https://user-images.githubusercontent.com/3375071/64480837-ce274580-d1a5-11e9-8b51-939c8aa54bac.png)

I can put in the URL to my netlify site and then log in with a user email and password, and then make edits, but it pushes them to github instead of the file system. If you have any tips that would be great! I will list the relevant parts of my code below.

Thank you!

### gatsby-config.js
```js
  plugins: [
    {
      resolve: "gatsby-plugin-netlify-cms",
      options: {
        modulePath: `${__dirname}/src/cms/cms.jsx`,
        manualInit: true,
      },
    },
    ...
    "gatsby-plugin-netlify", // at the very end
```

### cms.jsx
```jsx
/* eslint-disable @typescript-eslint/camelcase */
import CMS from "netlify-cms-app"
import { MdxControl, MdxPreview } from "netlify-cms-widget-mdx"
import FileSystemBackend from "netlify-cms-backend-fs"

const config = {}
if (process.env.NODE_ENV === "development") {
  config.backend = {
    name: "file-system",
    api_root: "/api",
  }
  config.display_url = "http://localhost:8000"
  CMS.registerBackend("file-system", FileSystemBackend)
} else {
  config.backend = {
    name: "git-gateway",
    accept_roles: ["admin", "editor"],
  }
}

CMS.registerWidget("mdx", MdxControl, MdxPreview)

// Start the CMS
CMS.init({ config })
```

### gatsby-node.js
```js
exports.onCreateDevServer = ({ app }) => {
  const fsMiddlewareAPI = require("netlify-cms-backend-fs/dist/fs")
  fsMiddlewareAPI(app)
}
```

**Comment by josmithua** [comment]
Issue solved: I still had my `backend` property in my `config.yml` file, so on `CMS.init({config})` it was merging the two configs and messing it up.

I removed the `backend` property from my config.yml file and it is working correctly 😃

**Comment by talves** [comment]
Glad you got it figured out. 😁

Merging these config settings are a little confusing until you start understanding how the pieces fit together. Making things too automated can come with it's own complications once someone starts to expand.
